import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../src/store.js';
import {Engine} from '../src/engine.js';
import type {Task} from '../src/types.js';

const fixture:Task={key:'local:task-1',hostId:'local',id:'task-1',cwd:'/repo',title:'Example',status:'running',owned:true,observedAt:Date.now(),updatedAt:Date.now(),messages:[],turnId:'turn-1',turnStatus:'inProgress'};
function setup(){const dir=mkdtempSync(join(tmpdir(),'astra-test-'));const s=new Store(join(dir,'db.sqlite'));return {dir,s,close:()=>{s.close();rmSync(dir,{recursive:true,force:true});}};}
test('watch settings and unresolved results survive a restart; repeated events do not resurrect handled items',()=>{
 const {dir,s,close}=setup();try{s.upsert(fixture);s.watch(fixture.key,true);s.manage(fixture.key);s.upsert({...fixture,status:'idle'});assert.equal(s.task(fixture.key)?.watched,true);assert.equal(s.task(fixture.key)?.managed,true);
 const a=s.action('completion','Done','Result',fixture.key,'completion:1');s.action('completion','Done','Duplicate',fixture.key,'completion:1');assert.equal(s.actions().length,1);
 const second=new Store(join(dir,'db.sqlite'));assert.equal(second.actions()[0].status,'open');second.resolve(a.id);second.close();s.action('completion','Done','Replay',fixture.key,'completion:1');assert.equal(s.actions()[0].status,'resolved');}finally{close();}
});
test('restart preserves ambiguous sends and expires connection-bound approvals',()=>{const {s,close}=setup();try{s.beginCommand('request-1',fixture.key,'send',{});s.action('approval','Approve','Command',fixture.key,'approval:1',{});s.recover();assert.equal(s.command('request-1').status,'uncertain');assert.equal(s.actions()[0].status,'expired');}finally{close();}});
test('same command ID cannot dispatch twice or be reused for another payload',async()=>{const {s,close}=setup();const e=new Engine({port:0,hosts:[]},s,'.');let count=0;try{await e.command('request-2',fixture.key,'message',{prompt:'hi'},async()=>{count++;return {ok:true};});await e.command('request-2',fixture.key,'message',{prompt:'hi'},async()=>{count++;});assert.equal(count,1);await assert.rejects(()=>e.command('request-2',fixture.key,'message',{prompt:'different'},async()=>{}),/different action/);}finally{close();}});
test('only watched task transitions create completion inbox entries',()=>{const {s,close}=setup();const e=new Engine({port:0,hosts:[]},s,'.');try{e.ingest(fixture);e.ingest({...fixture,status:'idle',turnStatus:'completed'});assert.equal(s.actions().length,0);s.watch(fixture.key,true);e.ingest({...fixture,turnId:'turn-2'});e.ingest({...fixture,turnId:'turn-2',turnStatus:'completed',status:'idle'});e.ingest({...fixture,turnId:'turn-2',turnStatus:'completed',status:'idle'});assert.equal(s.actions().length,1);}finally{close();}});
test('failed delivery is retained for user attention and never retried implicitly',async()=>{const {s,close}=setup();const e=new Engine({port:0,hosts:[]},s,'.');let count=0;try{await assert.rejects(()=>e.command('request-3',fixture.key,'message',{},async()=>{count++;throw new Error('connection closed');}));const r=await e.command('request-3',fixture.key,'message',{},async()=>{count++;});assert.equal(count,1);assert.equal(r.status,'uncertain');assert.equal(s.actions()[0].kind,'delivery');}finally{close();}});
test('approval responses are once-only and must match the live connection',()=>{const {s,close}=setup();const e=new Engine({port:0,hosts:[{id:'local',name:'Local',codex:'unused'}]},s,'.');const h=e.host('local');let calls=0;(h.rpc as any).respond=(_id:any,_r:any,g:string)=>{assert.equal(g,'connection-2');calls++;};try{e.event(h,{id:7,method:'item/commandExecution/requestApproval',params:{threadId:'task-1',turnId:'turn-1',command:'test'}},'connection-2');const a=s.actions()[0];e.approval(a.id,{action:'decline'});assert.equal(calls,1);assert.throws(()=>e.approval(a.id,{action:'accept'}),/no longer pending/);e.event(h,{method:'serverRequest/resolved',params:{threadId:'task-1',requestId:7}},'connection-2');assert.equal(s.actions()[0].status,'resolved');}finally{close();}});
test('offline machines retain their last snapshot without reporting a fresh observation',async()=>{const {s,close}=setup();const e=new Engine({port:0,hosts:[{id:'local',name:'Local',codex:'unused'}]},s,'.');const h=e.host('local');try{s.upsert(fixture);s.watch(fixture.key,true);h.lastSeen=123;(h as any).snapshot=async()=>{throw new Error('SSH unavailable');};await e.refreshHost(h);assert.equal(h.online,false);assert.equal(h.lastSeen,123);assert.equal(s.task(fixture.key)?.observedAt,fixture.observedAt);assert.equal(s.task(fixture.key)?.watched,true);}finally{close();}});
test('approval options that Codex did not offer cannot be submitted',()=>{const {s,close}=setup();const e=new Engine({port:0,hosts:[{id:'local',name:'Local',codex:'unused'}]},s,'.');const h=e.host('local');try{e.event(h,{id:8,method:'item/commandExecution/requestApproval',params:{threadId:'task-1',availableDecisions:['accept','cancel']}},'c');assert.throws(()=>e.approval(s.actions()[0].id,{action:'decline'}),/not available/);}finally{close();}});
