import {EventEmitter} from 'node:events';
import {existsSync,mkdirSync,readFileSync,renameSync,statSync,writeFileSync} from 'node:fs';
import {dirname} from 'node:path';
import {createHash,createPublicKey,generateKeyPairSync,sign} from 'node:crypto';
import {GatewayClient} from '@openclaw/gateway-client';
import type {AdapterName,ExecutionMetadata,Locality,Message,SourceConfig,SourceHealth,WorkCapabilities,WorkItem,WorkKind,WorkSourceRef,WorkStatus} from './types.js';
import {APP_VERSION} from './version.js';

export const MAX_EXCERPT=4000;
export const MAX_DETAIL_ENTRIES=30;
export const MAX_DETAIL_ENTRY=12000;
export const MAX_DETAIL_TOTAL=180000;

const observedCapabilities:WorkCapabilities={detail:true,deepLink:true,send:false,steer:false,pause:false,approve:false,git:false};
const HERMES_ALLOWED_PROFILES=new Set(['default','astra','qwen-local','peaktasks','peaktasks-sonnet','peaktasks-webchat']);
const bounded=(value:any,max=MAX_EXCERPT)=>typeof value==='string'?value.replaceAll('\u0000','').slice(0,max):'';
const timestamp=(value:any,fallback=Date.now())=>{const n=typeof value==='string'?Date.parse(value):Number(value);if(!Number.isFinite(n)||n<=0)return fallback;return n<10_000_000_000?n*1000:n;};
const rows=(value:any):any[]=>Array.isArray(value)?value:Array.isArray(value?.items)?value.items:Array.isArray(value?.data)?value.data:Array.isArray(value?.sessions)?value.sessions:Array.isArray(value?.chats)?value.chats:Array.isArray(value?.messages)?value.messages:[];
const inventoryRows=(value:any,label:string)=>{const result=rows(value);if(!Array.isArray(value)&&!['items','data','sessions','chats'].some(key=>Array.isArray(value?.[key])))throw new Error(`${label} returned an incompatible inventory payload`);return result;};
const loopback=(value:string)=>{const url=new URL(value),host=url.hostname.toLowerCase();if(!['localhost','127.0.0.1','::1','[::1]'].includes(host)&&!host.startsWith('127.'))throw new Error('Source endpoints must be loopback-only');return value;};
const bool=(value:any)=>value===true||value===1||value==='true';
const explicitLocality=(...values:any[]):Locality=>{for(const value of values){const v=String(value||'').toLowerCase();if(['local','cloud','hybrid'].includes(v))return v as Locality;}return 'unknown';};
const safeMetadata=(value:any)=>value&&typeof value==='object'?Object.fromEntries(Object.entries(value).filter(([key,item])=>!/token|secret|key|auth|prompt|content|message/i.test(key)&&['string','number','boolean'].includes(typeof item)).slice(0,20).map(([key,item])=>[key,typeof item==='string'?bounded(item,200):item])):undefined;
const mappedLocality=(values:Record<string,Locality>|undefined,key:string|undefined)=>{if(!values||!key)return 'unknown';const match=Object.entries(values).find(([candidate])=>candidate.toLowerCase()===key.toLowerCase());return match?.[1]||'unknown';};
const modelInfo=(row:any,hostId:string,config?:SourceConfig,profile?:string):ExecutionMetadata=>{const provider=bounded(row.provider||row.model_provider||row.modelProvider||row.meta?.provider,120)||undefined,requestedModel=bounded(row.requested_model||row.requestedModel||row.model||row.models?.[0],300)||undefined,resolvedModel=bounded(row.resolved_model||row.resolvedModel||row.actual_model||row.actualModel||row.meta?.resolved_model,300)||undefined,reported=explicitLocality(row.locality,row.inference_location,row.inferenceLocation,row.execution_locality,row.executionLocality,row.meta?.locality),locality=reported!=='unknown'?reported:mappedLocality(config?.locality?.providers,provider)!=='unknown'?mappedLocality(config?.locality?.providers,provider):mappedLocality(config?.locality?.models,resolvedModel||requestedModel)!=='unknown'?mappedLocality(config?.locality?.models,resolvedModel||requestedModel):mappedLocality(config?.locality?.profiles,profile);return {host:String(row.execution_host||row.executionHost||row.host||row.machine||hostId),provider,requestedModel,resolvedModel,locality};};
const latestText=(value:any)=>bounded(value?.latest_excerpt||value?.latestExcerpt||value?.preview||value?.last_message?.content||value?.last_message||value?.lastMessage?.content||value?.lastMessage?.text||value?.lastMessage||value?.summary||value?.title||'');
const messageText=(message:any)=>bounded(message?.content?.text||message?.content||message?.text||message?.message||'',MAX_DETAIL_ENTRY);
const role=(value:any)=>{const v=String(value||'assistant').toLowerCase();return ['user','assistant','tool','system','change'].includes(v)?v:'assistant';};
const exactCorrelations=(row:any):string[]=>{
 const values=[row.correlation_id,row.correlationId,row.session_correlation_id,row.propagated_session_id,row.external_session_id];
 return [...new Set(values.filter(value=>typeof value==='string'&&value.trim()).map(value=>value.trim()))];
};

function token(path:string){
 const st=statSync(path);if((st.mode&0o077)!==0)throw new Error('Credential file permissions must be 0600');
 const value=readFileSync(path,'utf8').trim();if(!value)throw new Error('Credential file is empty');return value;
}
function endpoint(base:string,path:string){return base.replace(/\/$/,'')+path;}
function safeError(error:any){return String(error?.message||error||'Source request failed').replace(/Bearer\s+\S+/gi,'Bearer [redacted]').replace(/token[=: ]+\S+/gi,'token=[redacted]').slice(0,500);}
async function mapLimit<T,R>(values:T[],limit:number,work:(value:T)=>Promise<R>):Promise<R[]>{const output=new Array<R>(values.length);let next=0;await Promise.all(Array.from({length:Math.min(limit,values.length)},async()=>{while(next<values.length){const index=next++;output[index]=await work(values[index]);}}));return output;}
async function requestJson(base:string,path:string,secret:string,headers:Record<string,string>={},timeout=10000){
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeout);
 try{const response=await fetch(endpoint(base,path),{headers:{Accept:'application/json',Authorization:`Bearer ${secret}`,...headers},signal:controller.signal});if(!response.ok)throw new Error(`Source returned HTTP ${response.status}`);return await response.json();}
 finally{clearTimeout(timer);}
}
export function boundDetailMessages(input:any[]):Message[]{let total=0;const result:Message[]=[];for(const [index,value] of input.slice(-MAX_DETAIL_ENTRIES).entries()){const text=messageText(value);if(!text)continue;let remaining=MAX_DETAIL_TOTAL-total;if(remaining<=0)break;const clipped=text.slice(0,Math.min(MAX_DETAIL_ENTRY,remaining));total+=clipped.length;remaining=MAX_DETAIL_TOTAL-total;const output=bounded(value.output,Math.min(MAX_DETAIL_ENTRY,Math.max(0,remaining)))||undefined;total+=output?.length||0;result.push({id:String(value.id||value.message_id||index),role:role(value.role||value.sender),text:clipped,phase:value.phase,at:timestamp(value.created_at||value.timestamp||value.at,0)||undefined,status:value.status,exitCode:value.exitCode,output});}return result;}

export interface SourceObservation {item:WorkItem;source:WorkSourceRef;correlations:string[];native:any;eventId?:string;eventKind?:'failure'|'blocked'|'approval'|'completion';eventBody?:string;}
export interface WorkDetail {messages:Message[];}

export abstract class SourceAdapter extends EventEmitter {
 health:SourceHealth;
 protected secret?:string;
 constructor(public config:SourceConfig){super();loopback(config.baseUrl);this.health={id:config.id,adapter:config.adapter,name:config.name||config.adapter,hostId:config.hostId,online:false,stale:true,lastSeen:0,error:'Not yet connected',activeCount:0,itemCount:0};}
 protected credential(){return this.secret??=token(this.config.tokenFile);}
 protected ok(activeCount:number,itemCount:number,version?:string){this.health={...this.health,online:true,stale:false,lastSeen:Date.now(),error:'',activeCount,itemCount,...(version?{version}:{})};}
 protected failed(error:any){this.health={...this.health,online:false,stale:this.health.lastSeen===0||Date.now()-this.health.lastSeen>45000,error:safeError(error)};}
 abstract inventory():Promise<SourceObservation[]>;
 abstract detail(nativeId:string,source:WorkSourceRef):Promise<WorkDetail>;
 async modelCatalog():Promise<any[]>{return [];}
 close(){}
}

function item(source:WorkSourceRef,data:Partial<WorkItem>&Pick<WorkItem,'title'|'updatedAt'|'observedAt'|'status'|'statusConfidence'|'kind'|'execution'>):WorkItem{
 const id=`${source.adapter}:${source.sourceId}:${source.nativeId}`;
 const excerpt=bounded(data.latestExcerpt||data.latest?.text||'');
 return {key:id,id,kind:data.kind,title:bounded(data.title,500)||'Untitled work',status:data.status,statusConfidence:data.statusConfidence,updatedAt:data.updatedAt,observedAt:data.observedAt,createdAt:data.createdAt,archived:!!data.archived,pinned:!!data.pinned,watched:!!data.watched,latestExcerpt:excerpt||undefined,sourceRefs:[source],execution:data.execution,hostId:source.hostId,cwd:data.cwd||'',projectId:data.projectId,branch:data.branch,latest:excerpt?{id:`latest:${source.nativeId}`,role:'assistant',text:excerpt,at:data.updatedAt}:undefined,messages:[],model:data.execution.requestedModel||data.execution.resolvedModel,error:data.error,managed:false,owned:null};
}

export class HermesAdapter extends SourceAdapter {
 declare config:Extract<SourceConfig,{adapter:'hermes'}>;
 async inventory(){
  try{const secret=this.credential(),out:SourceObservation[]=[];
   for(const profile of this.config.profiles.filter(value=>HERMES_ALLOWED_PROFILES.has(value))){let offset=0;for(let page=0;page<20;page++){
    const result=await requestJson(this.config.baseUrl,`/api/profiles/sessions?profile=${encodeURIComponent(profile)}&archived=include&order=recent&limit=500&offset=${offset}`,secret,{'X-Hermes-Session-Token':secret},20000);const batch=inventoryRows(result,'Hermes');for(const row of batch){if(bool(row.archived||row.is_archived)&&!bool(row.pinned||row.is_pinned))continue;const native=String(row.id||row.session_id||'');if(!native)continue;const now=Date.now(),updated=timestamp(row.last_active||row.updated_at||row.modified_at||row.created_at,now),active=bool(row.is_active),ref:WorkSourceRef={adapter:'hermes',sourceId:this.config.id,hostId:this.config.hostId,nativeId:`${profile}:${native}`,profile,deepLink:row.deep_link||row.url,capabilities:{...observedCapabilities,deepLink:!!(row.deep_link||row.url)}};const execution=modelInfo(row,this.config.hostId,this.config,profile);out.push({source:ref,correlations:exactCorrelations(row),native:{sessionId:native,profile,source:bounded(row.source,100),workspace:bounded(row.workspace||row.cwd,1000),usage:safeMetadata(row.usage)},item:item(ref,{title:row.title||row.name||`Hermes session ${native.slice(0,8)}`,kind:row.source==='cron'||row.kind==='automation'?'automation':'agent-task',status:active?'recent':row.error?'failed':row.ended_at?'completed':'idle',statusConfidence:'heuristic',updatedAt:updated,observedAt:now,createdAt:timestamp(row.created_at,updated),archived:bool(row.archived||row.is_archived),pinned:bool(row.pinned||row.is_pinned),latestExcerpt:latestText(row),cwd:bounded(row.workspace||row.cwd,1000),execution,error:bounded(row.error,1000)||undefined})});}
    if(batch.length<500)break;offset+=batch.length;
   }}this.ok(out.filter(value=>value.item.status==='recent').length,out.length,String((out[0]?.native as any)?.version||''));return out;
  }catch(error){this.failed(error);throw error;}
 }
 async detail(_nativeId:string,source:WorkSourceRef){try{const secret=this.credential(),native=source.nativeId.slice(source.nativeId.indexOf(':')+1),result=await requestJson(this.config.baseUrl,`/api/sessions/${encodeURIComponent(native)}/messages?profile=${encodeURIComponent(source.profile||'default')}&limit=${MAX_DETAIL_ENTRIES}&order=latest`,secret,{'X-Hermes-Session-Token':secret});return {messages:boundDetailMessages(rows(result))};}catch(error){this.failed(error);throw error;}}
 async modelCatalog(){try{const secret=this.credential(),result=await requestJson(this.config.baseUrl,`/api/model/options?profile=${encodeURIComponent(this.config.profiles[0]||'default')}`,secret,{'X-Hermes-Session-Token':secret});return rows(result);}catch{return [];}}
}

function openWebUIMessages(detail:any){const chat=detail?.chat||detail;const direct=rows(chat?.messages);if(direct.length)return direct;const history=chat?.history?.messages;if(history&&typeof history==='object')return Object.values(history).sort((a:any,b:any)=>timestamp(a?.timestamp,0)-timestamp(b?.timestamp,0));return [];}
export class OpenWebUIAdapter extends SourceAdapter {
 declare config:Extract<SourceConfig,{adapter:'openwebui'}>;
 private details=new Map<string,{updatedAt:number;detail:any}>();
 private async chat(id:string,updatedAt=0){const cached=this.details.get(id);if(cached&&cached.updatedAt===updatedAt)return cached.detail;const detail=await requestJson(this.config.baseUrl,`/api/v1/chats/${encodeURIComponent(id)}`,this.credential());this.details.set(id,{updatedAt,detail});return detail;}
 async inventory(){try{
  const listed:any[]=[];for(let page=1;page<=20;page++){const result=await requestJson(this.config.baseUrl,`/api/v1/chats/list?page=${page}&include_pinned=true&sort_by=updated_at&sort_dir=desc`,this.credential());const batch=inventoryRows(result,'Open WebUI');listed.push(...batch);if(batch.length<60)break;}
  const pinnedResult=await requestJson(this.config.baseUrl,'/api/v1/chats/pinned',this.credential()).catch(()=>[]),pinned=inventoryRows(pinnedResult,'Open WebUI pinned inventory'),byId=new Map<string,any>();for(const row of [...listed,...pinned])if(row?.id)byId.set(String(row.id),{...byId.get(String(row.id)),...row,pinned:bool(row.pinned)||pinned.includes(row)});
  const visible=[...byId.values()].filter(row=>!bool(row.archived||row.is_archived)||bool(row.pinned));const out=await mapLimit(visible,6,async(row):Promise<SourceObservation>=>{const native=String(row.id),now=Date.now(),updated=timestamp(row.updated_at||row.timestamp||row.created_at,now);let detail:any={};if(!row.last_message&&!row.preview){try{detail=await this.chat(native,updated);}catch{}}const chat=detail?.chat||detail,rowData={...chat,...row},messages=openWebUIMessages(detail),last=messages.at(-1),deepLink=this.config.deepLinkBase?endpoint(this.config.deepLinkBase,row.share_id?`/s/${row.share_id}`:`/c/${native}`):undefined,ref:WorkSourceRef={adapter:'openwebui',sourceId:this.config.id,hostId:this.config.hostId,nativeId:native,deepLink,capabilities:{...observedCapabilities,deepLink:!!deepLink}},execution=modelInfo(rowData,this.config.hostId,this.config),active=bool(row.active??chat.active);return {source:ref,correlations:exactCorrelations(rowData),native:{chatId:native},item:item(ref,{title:row.title||chat.title||'Open WebUI chat',kind:'conversation',status:active?'active':row.error?'failed':'idle',statusConfidence:'authoritative',updatedAt:updated,observedAt:now,createdAt:timestamp(row.created_at||chat.created_at,updated),archived:bool(row.archived||row.is_archived),pinned:bool(row.pinned),latestExcerpt:messageText(last)||latestText(row),execution,error:bounded(row.error,1000)||undefined})};});this.ok(out.filter(value=>value.item.status==='active').length,out.length);return out;
 }catch(error){this.failed(error);throw error;}}
 async detail(nativeId:string){try{const detail=await this.chat(nativeId);return {messages:boundDetailMessages(openWebUIMessages(detail))};}catch(error){this.failed(error);throw error;}}
 async modelCatalog(){try{return rows(await requestJson(this.config.baseUrl,'/api/models',this.credential()));}catch{return [];}}
}

interface OpenClawDeviceState {deviceId:string;privateKeyPem:string;publicKeyPem:string;deviceToken?:string;scopes?:string[];}
function publicKeyRaw(publicKeyPem:string){const der=createPublicKey(publicKeyPem).export({format:'der',type:'spki'}) as Buffer;return der.subarray(-32).toString('base64url');}
function readOpenClawDevice(path:string):OpenClawDeviceState{
 if(existsSync(path)){const st=statSync(path);if((st.mode&0o077)!==0)throw new Error('OpenClaw device file permissions must be 0600');const saved=JSON.parse(readFileSync(path,'utf8'));if(!saved.deviceId||!saved.privateKeyPem||!saved.publicKeyPem)throw new Error('OpenClaw device file is invalid');return saved;}
 const pair=generateKeyPairSync('ed25519'),privateKeyPem=pair.privateKey.export({format:'pem',type:'pkcs8'}).toString(),publicKeyPem=pair.publicKey.export({format:'pem',type:'spki'}).toString(),raw=publicKeyRaw(publicKeyPem),state={deviceId:createHash('sha256').update(Buffer.from(raw,'base64url')).digest('hex'),privateKeyPem,publicKeyPem};mkdirSync(dirname(path),{recursive:true,mode:0o700});const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,JSON.stringify(state,null,2),{encoding:'utf8',mode:0o600,flag:'wx'});renameSync(temporary,path);return state;
}
function writeOpenClawDevice(path:string,state:OpenClawDeviceState){const temporary=`${path}.${process.pid}.tmp`;writeFileSync(temporary,JSON.stringify(state,null,2),{encoding:'utf8',mode:0o600,flag:'wx'});renameSync(temporary,path);}
function openClawAgent(row:any){const direct=bounded(row.agentId||row.agent,200);if(direct)return direct;const match=String(row.key||row.id||'').match(/^agent:([^:]+):/);return bounded(match?.[1],200)||undefined;}
function encodeOpenClawNative(row:any){return Buffer.from(JSON.stringify([String(openClawAgent(row)||''),String(row.key||row.id||''),String(row.sessionId||'')])).toString('base64url');}
function decodeOpenClawNative(nativeId:string){try{const decoded=JSON.parse(Buffer.from(nativeId,'base64url').toString('utf8'));return {agentId:String(decoded[0]||''),sessionKey:String(decoded[1]||''),sessionId:String(decoded[2]||'')};}catch{return {agentId:'',sessionKey:nativeId,sessionId:''};}}

export class OpenClawAdapter extends SourceAdapter {
 declare config:Extract<SourceConfig,{adapter:'openclaw'}>;
 private client?:GatewayClient;private connectPromise?:Promise<void>;private connected=false;private subscribed=false;private bootstrapDirty=false;private device?:OpenClawDeviceState;
 private state(){return this.device??=readOpenClawDevice(this.config.deviceFile);}
 private rpc(method:'sessions.subscribe'|'sessions.list'|'chat.history',params:any):Promise<any>{return this.client!.request(method,params,{timeoutMs:12000});}
 private async connect(){if(this.connected)return;if(this.connectPromise)return this.connectPromise;const device=this.state(),deferred:Record<string,(value?:any)=>void>={};this.connectPromise=new Promise<void>((resolve,reject)=>{deferred.resolve=resolve;deferred.reject=reject;});this.client=new GatewayClient({url:this.config.baseUrl,token:device.deviceToken?undefined:this.credential(),deviceToken:device.deviceToken,deviceIdentity:device,clientName:'gateway-client',clientDisplayName:'Astra Control',clientVersion:APP_VERSION,mode:'ui',platform:process.platform,deviceFamily:'server',role:'operator',scopes:['operator.read','operator.approvals'],caps:['approvals','exec-approvals','plugin-approvals','session-scoped-events'],commands:[],permissions:{},minProtocol:4,maxProtocol:4,hostDeps:{signDevicePayload:(privateKeyPem,payload)=>sign(null,Buffer.from(payload),privateKeyPem).toString('base64url'),publicKeyRawBase64UrlFromPem:publicKeyRaw,loadDeviceAuthToken:()=>device.deviceToken?{token:device.deviceToken,scopes:device.scopes}:null,storeDeviceAuthToken:({token,scopes})=>{device.deviceToken=token;device.scopes=scopes;writeOpenClawDevice(this.config.deviceFile,device);},clearDeviceAuthToken:()=>{delete device.deviceToken;delete device.scopes;writeOpenClawDevice(this.config.deviceFile,device);},redactForLog:safeError},onHelloOk:()=>{this.connected=true;this.subscribed=false;deferred.resolve();},onConnectError:error=>{if(!this.connected)deferred.reject(error);this.failed(error);},onClose:()=>{this.connected=false;this.subscribed=false;const prior=this.health.error;this.health={...this.health,online:false,stale:this.health.lastSeen===0||Date.now()-this.health.lastSeen>45000,error:prior&&prior!=='Not yet connected'?prior:'OpenClaw Gateway disconnected'};this.emit('invalidate',{sourceId:this.config.id});},onGap:()=>{this.bootstrapDirty=true;this.emit('invalidate',{sourceId:this.config.id,event:'sequence-gap'});},onEvent:event=>this.onEvent(event)});this.client.start();try{await this.connectPromise;}finally{this.connectPromise=undefined;}}
 private onEvent(frame:any){const name=String(frame.event||''),payload=frame.payload||{},sessionKey=payload.sessionKey||payload.session?.key;if(name==='sessions.changed'&&payload.session)this.bootstrapDirty=true;if(['session.approval','exec.approval.requested','plugin.approval.requested'].includes(name)){const pending=payload.state?payload.state==='pending':!name.endsWith('.resolved');if(pending)this.emit('action',{sourceId:this.config.id,sessionKey,eventId:String(payload.id||payload.approvalId||frame.seq),kind:'approval',title:'OpenClaw approval needs attention',body:bounded(payload.reason||payload.message||'Review the approval in OpenClaw.',5000)});}if(name==='chat'&&payload.state==='error')this.emit('action',{sourceId:this.config.id,sessionKey,eventId:String(payload.runId||payload.id||frame.seq),kind:'failure',title:'OpenClaw work needs attention',body:bounded(payload.errorMessage||payload.errorDetail?.providerErrorMessagePreview||'A run failed.',5000)});if(['sessions.changed','session.message','session.operation','session.tool','session.approval','chat'].includes(name))this.emit('invalidate',{sourceId:this.config.id,event:name});}
 private async roster(){const params={limit:500,configuredAgentsOnly:this.config.configuredAgentsOnly!==false,includeDerivedTitles:true,includeLastMessage:true};this.bootstrapDirty=false;if(!this.subscribed){await this.rpc('sessions.subscribe',{});this.subscribed=true;}const listPages=async(archived=false)=>{let result=await this.rpc('sessions.list',{...params,...(archived?{archived:true}:{})}),resultRows=rows(result),next=result?.nextOffset,hasMore=bool(result?.hasMore);for(let page=0;hasMore&&page<20;page++){result=await this.rpc('sessions.list',{...params,...(archived?{archived:true}:{}),offset:next});resultRows.push(...rows(result));next=result?.nextOffset;hasMore=bool(result?.hasMore);}return resultRows;};let resultRows=[...await listPages(),...await listPages(true)];if(this.bootstrapDirty)resultRows=[...await listPages(),...await listPages(true)];const unique=new Map<string,any>();for(const row of resultRows)if(!bool(row.archived)||bool(row.pinned))unique.set(encodeOpenClawNative(row),row);return [...unique.values()];}
 async inventory(){try{await this.connect();const roster=await this.roster(),out=roster.map(row=>this.observation(row)).filter(Boolean) as SourceObservation[];this.ok(out.filter(value=>value.item.status==='active').length,out.length);return out;}catch(error){this.failed(error);throw error;}}
 private observation(row:any):SourceObservation|null{const sessionKey=String(row.key||row.id||'');if(!sessionKey)return null;const native=encodeOpenClawNative(row),now=Date.now(),updated=timestamp(row.updatedAt||row.lastInteractionAt||row.lastActivityAt||row.createdAt,now),nativeStatus=String(row.status||'').toLowerCase(),active=(Array.isArray(row.activeRunIds)&&row.activeRunIds.length>0)||bool(row.hasActiveRun)||nativeStatus==='running',status:WorkStatus=active?'active':row.waiting||nativeStatus==='waiting'?'waiting':['failed','killed','timeout'].includes(nativeStatus)||bool(row.failed)?'failed':nativeStatus==='done'?'completed':'idle',agent=openClawAgent(row),ref:WorkSourceRef={adapter:'openclaw',sourceId:this.config.id,hostId:this.config.hostId,nativeId:native,agent,deepLink:row.deepLink||row.url,capabilities:{...observedCapabilities,deepLink:!!(row.deepLink||row.url)}},execution=modelInfo(row,this.config.hostId,this.config);return {source:ref,correlations:exactCorrelations(row),native:{sessionKey,sessionId:row.sessionId,agentId:agent},item:item(ref,{title:row.title||row.derivedTitle||row.displayName||row.label||`OpenClaw ${agent||'session'}`,kind:row.kind==='automation'||row.kind==='cron'||row.channel==='cron'?'automation':'agent-task',status,statusConfidence:'authoritative',updatedAt:updated,observedAt:now,createdAt:timestamp(row.sessionStartedAt||row.createdAt,updated),archived:bool(row.archived),pinned:bool(row.pinned),latestExcerpt:latestText(row),cwd:bounded(row.workspace||row.cwd,1000),execution,error:bounded(row.error||row.lastError,1000)||undefined})};}
 async detail(nativeId:string){try{await this.connect();const native=decodeOpenClawNative(nativeId),result=await this.rpc('chat.history',{sessionKey:native.sessionKey,limit:MAX_DETAIL_ENTRIES,maxChars:MAX_DETAIL_TOTAL,...(native.agentId?{agentId:native.agentId}:{})});return {messages:boundDetailMessages(rows(result?.messages||result))};}catch(error){this.failed(error);throw error;}}
 close(){this.client?.stop();this.connected=false;}
}

export function createAdapter(config:SourceConfig):SourceAdapter{if(config.adapter==='hermes')return new HermesAdapter(config);if(config.adapter==='openwebui')return new OpenWebUIAdapter(config);return new OpenClawAdapter(config);}
export function adapterLabel(adapter:AdapterName){return adapter==='openwebui'?'Open WebUI':adapter==='openclaw'?'OpenClaw':adapter==='hermes'?'Hermes':'Codex';}
