import {readFileSync,statSync} from 'node:fs';
import type {RuntimeConfig,RuntimeSnapshot} from './types.js';

const empty=():RuntimeSnapshot=>({observedAt:0,online:false,error:'Not yet connected',catalog:[],router:null,metrics:{},loadedModels:[],providers:[]});
const safe=(error:any)=>String(error?.message||error||'Runtime request failed').replace(/Bearer\s+\S+/gi,'Bearer [redacted]').slice(0,500);
const list=(value:any):any[]=>Array.isArray(value)?value:Array.isArray(value?.data)?value.data:Array.isArray(value?.models)?value.models:[];
function safeRuntimeValue(value:any,depth=0):any{if(depth>3)return undefined;if(typeof value==='string')return value.slice(0,300);if(typeof value==='number'||typeof value==='boolean'||value===null)return value;if(Array.isArray(value))return value.slice(0,50).map(item=>safeRuntimeValue(item,depth+1)).filter(item=>item!==undefined);if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).filter(([key])=>!/token|secret|credential|auth|prompt|content|message|header|cookie/i.test(key)).slice(0,60).map(([key,item])=>[key,safeRuntimeValue(item,depth+1)]).filter(([,item])=>item!==undefined));return undefined;}

export class RuntimeMonitor {
 snapshot:RuntimeSnapshot=empty();private secret?:string;
 constructor(public config?:RuntimeConfig){if(config){for(const value of [config.baseUrl,...(config.loadedModelUrls||[])]){const url=new URL(value),host=url.hostname.toLowerCase();if(!['localhost','127.0.0.1','::1','[::1]'].includes(host)&&!host.startsWith('127.'))throw new Error('Runtime endpoint must be loopback-only');}}}
 private credential(){if(!this.config?.tokenFile)return '';if(this.secret)return this.secret;const st=statSync(this.config.tokenFile);if((st.mode&0o077)!==0)throw new Error('Runtime credential file permissions must be 0600');return this.secret=readFileSync(this.config.tokenFile,'utf8').trim();}
 private async request(path:string,text=false){if(!this.config)throw new Error('Runtime is not configured');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000),secret=this.credential();try{const response=await fetch(this.config.baseUrl.replace(/\/$/,'')+path,{headers:{Accept:text?'text/plain':'application/json',...(secret?{Authorization:`Bearer ${secret}`}:{})},signal:controller.signal});if(!response.ok)throw new Error(`Runtime returned HTTP ${response.status}`);return text?response.text():response.json();}finally{clearTimeout(timer);}}
 private async requestUrl(url:string){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000),secret=this.credential();try{const response=await fetch(url,{headers:{Accept:'application/json',...(secret?{Authorization:`Bearer ${secret}`}:{})},signal:controller.signal});if(!response.ok)throw new Error(`Runtime returned HTTP ${response.status}`);return response.json();}finally{clearTimeout(timer);}}
 async refresh(){if(!this.config)return this.snapshot;const loadedRequests=(this.config.loadedModelUrls?.length?this.config.loadedModelUrls:[`${this.config.baseUrl.replace(/\/$/,'')}/api/ps`]).map(url=>this.requestUrl(url));const [catalog,router,metrics,...loaded]=await Promise.allSettled([this.request('/v1/models'),this.request('/router/status'),this.request('/metrics',true),...loadedRequests]);const successes=[catalog,router,metrics,...loaded].filter(value=>value.status==='fulfilled').length;if(!successes){const reason=(catalog as PromiseRejectedResult).reason;this.snapshot={...this.snapshot,online:false,error:safe(reason)};return this.snapshot;}const metricValues:Record<string,number>={};if(metrics.status==='fulfilled'){for(const line of String(metrics.value).split('\n')){const match=line.match(/^(astra_(?:gpu|router|model)_[a-zA-Z0-9_:]+)(?:\{[^}]*\})?\s+(-?\d+(?:\.\d+)?)$/);if(match)metricValues[match[1]]=Number(match[2]);}}const modelRows=catalog.status==='fulfilled'?list(catalog.value):[],loadedRows=loaded.flatMap(result=>result.status==='fulfilled'?list(result.value):[]).filter(value=>{const status=String(value?.status?.value||value?.status||'').toLowerCase();return !status||status==='loaded'||status==='running'||status==='active';}),normalizedLoaded=new Map<string,any>();for(const value of loadedRows){const id=String(value.id||value.name||value.model||'').slice(0,300);if(id)normalizedLoaded.set(id,{id,size:typeof value.size==='number'?value.size:undefined,expiresAt:value.expires_at||value.expiresAt});}this.snapshot={observedAt:Date.now(),online:true,error:'',catalog:modelRows.slice(0,1000).map(value=>({id:String(value.id||value.name||'').slice(0,300),provider:String(value.provider||value.owned_by||'').slice(0,120)||undefined,locality:['local','cloud','hybrid'].includes(value.locality)?value.locality:'local'})),router:router.status==='fulfilled'?safeRuntimeValue(router.value):null,metrics:metricValues,loadedModels:[...normalizedLoaded.values()].slice(0,100),providers:[...new Set(modelRows.map(value=>String(value.provider||value.owned_by||'').slice(0,120)).filter(Boolean))]};return this.snapshot;}
}
